# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: project-sync-ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          SOURCE_PROJECT_KEY: "source-project-key"
          SOURCE_CLIENT_ID: "sourceClientId"
          SOURCE_CLIENT_SECRET: "sourceClientSecret"
          SOURCE_AUTH_URL: "https://auth.eu-central-1.aws.commercetools.com/"
          SOURCE_API_URL: "https://api.eu-central-1.aws.commercetools.com/"
          TARGET_PROJECT_KEY: "target-project-key"
          TARGET_CLIENT_ID: "targetClientId"
          TARGET_CLIENT_SECRET: "targetClientSecret"
          TARGET_AUTH_URL: "https://auth.eu-central-1.aws.commercetools.com/"
          TARGET_API_URL: "https://api.eu-central-1.aws.commercetools.com/"
